AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  VanityNumberFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: VanityNumbers
      Policies:
        - DynamoDBCrudPolicy:
            TableName: VanityNumbers

  VanityNumbersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: VanityNumbers
      AttributeDefinitions:
        - AttributeName: callerNumber
          AttributeType: S
      KeySchema:
        - AttributeName: callerNumber
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
